export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const REVIEW_TEMPLATE_ADD = "REVIEW_TEMPLATE_ADD";
export const REVIEW_TEMPLATE_FETCH = "REVIEW_TEMPLATE_FETCH";
export const EMPLOYEE_REVIEW_ADD = "EMPLOYEE_REVIEW_ADD";
export const REVIEW_ANSWER_SUBMIT = "REVIEW_ANSWER_SUBMIT";
